---
repos:
    # pre commit general files stuff
    - repo: meta
      hooks:
          - id: check-useless-excludes
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: check-added-large-files
          - id: check-case-conflict
          - id: check-json
          - id: check-symlinks
            args: [--autofix]
          - id: check-yaml
          - id: destroyed-symlinks
          - id: detect-private-key
          - id: end-of-file-fixer
          - id: fix-byte-order-marker
          - id: trailing-whitespace
          - id: mixed-line-ending
            args: [--fix=auto]
          - id: pretty-format-json
            args: [--autofix, --no-sort-keys]
    - repo: https://github.com/devoteamgcloud/pre-commit-dataform
      rev: v1.0.2
      hooks:
        - id: dataform_format
